# Generated by Django 5.0.4 on 2024-04-14 19:13

import ai.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='URL (пример: имя_пользователя)')),
                ('first_name', models.CharField(default='name', max_length=100, verbose_name='Имя')),
                ('last_name', models.CharField(default='surname', max_length=100, verbose_name='Фамилия')),
                ('email', models.EmailField(default='example@gmail.com', max_length=254, verbose_name='Эл. почта')),
                ('avatar', models.ImageField(upload_to='avatars/', validators=[ai.models.validate_square_image], verbose_name='Фото профиля')),
                ('user', models.OneToOneField(default='Пользователь', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Имя пользователя (ваше имя, отображаемое на сайте)')),
            ],
            options={
                'verbose_name_plural': 'Профили пользователей',
            },
        ),
    ]
