# Generated by Django 5.0.4 on 2024-04-14 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='first_name',
            field=models.CharField(default='name', max_length=100, verbose_name='Никнейм'),
        ),
    ]
